name: Promotion CI

on:
  pull_request:
    paths:
      - 'apps/promotion/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'turbo.json'

jobs:
  promotion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      # -----------------------
      # BUILD
      # -----------------------
      - name: Build promotion
        run: |
          pnpm turbo run build \
            --filter=@turbo-ci-cd/promotion...

      # -----------------------
      # TEST
      # -----------------------
      - name: Test promotion
        run: |
          pnpm turbo run test \
            --filter=@turbo-ci-cd/promotion...

      # -----------------------
      # E2E
      # -----------------------
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: E2E promotion
        run: |
          pnpm turbo run preview --filter=@turbo-ci-cd/promotion... &
          pnpm turbo run test-e2e --filter=@turbo-ci-cd/promotion...
